---
  # Neuron parameters
  N: {
      e: 400,
      i: 100
    }
  a: {
      e: 0.02,
      i: 0.1
    }
  b: {
      e: 0.2,
      i: 0.2
    }
  c: {
      e: -65,
      i: -65
    }
  d: {
      e: 8,
      i: 2
    }
  v-init: {
      e: -65,
      i: -65
    }
  # Synapse parameters
  architecture: "small-world"
  small-world-params: {
      k: 50,
      p: 0.33
    }
  scale: {
      e: 3,
      i: 1
    }
  delay: {
      e: {
        min: 1,
        max: 20
      },
      i: {
        min: 1,
        max: 1
      }
    }
  # Recording parameters
  history-limit: 1000
